### ISSUE TITLE
(example): not friendly UX when trying to sign in before registering

### ISSUE THREAD

**Issue by SimoMay** [teamhanko/hanko#83]
Clicking on `Sign in with passkey` before creating a user or registering the device causes confusion.

The example client will get the publicKey.challenge and initiate the process before requesting an email and checking if we do have user/device registered first.

**Before a user is created:**
<img width="720" alt="Screenshot 2022-06-16 at 16 55 40" src="https://user-images.githubusercontent.com/1516966/174098929-f3a2285c-de38-4a4a-bb00-408fbc84fb02.png">

**After a user is created:**
<img width="731" alt="Screenshot 2022-06-16 at 16 54 52" src="https://user-images.githubusercontent.com/1516966/174098862-b830f3da-c5ae-4552-93c8-3530b77cab30.png">

**Solution:**
BestBuy flow seems reasonable, you can do email login flow, or you click on `Sign in with WebAuthn`, it routes to a form to fill in the email first, checks that it's possible, respond with an error that it's not possible till it's setup first.

<img width="1065" alt="Screenshot 2022-06-16 at 16 47 58" src="https://user-images.githubusercontent.com/1516966/174099557-01effbdf-b0cf-416a-b7f8-b527774a7a2e.png">

<img width="1063" alt="Screenshot 2022-06-16 at 16 48 05" src="https://user-images.githubusercontent.com/1516966/174099584-b39cee00-4a54-4824-aa47-11e628e102fc.png">

<img width="1059" alt="Screenshot 2022-06-16 at 16 47 44" src="https://user-images.githubusercontent.com/1516966/174099621-1671535e-9b1d-4b73-810e-05619af8e0a4.png">

**Comment by bjoern-m** [comment]
Hi @SimoMay,

Thank you for your feedback. I have looked into it and guess one problem is, that during the WebAuthn finalization several things can go wrong and the API uses different status codes, but only one status code translates into the "Invalid WebAuthn credentials" error. Not sure what in your case triggered the "Technical error" but I see space for improvement here. Will create a PR shortly, so that hopefully in both cases described, the same error occurs.

The other question is whether we can improve the login flow. I think theoretically we could determine from the credential assertion response whether the user exists and display a registration page with an email input. But the assumption that a user wants to register a new account in this case might be wrong. And what are the real cases the error gets displayed?

When the browser noticed there is no WebAuthn credential for the current origin, the browser displays an error message. So the sign in fails before there is a credential assertion. And when you've chosen a credential that has maybe been removed from the database, it's reasonable you get an "Invalid WebAuthn credential error". Another thing is that on Apple devices, for example, WebAuthn credentials cannot be used across browsers, and a credential registered on a Windows device will not work on an Apple device and vice versa. So the user account is in place, but on the current device there is no WebAuthn credential registered yet. Then the way to log in is to fill in the email input and after entering the passcode or password
the UI presents the Webauthn credential registration page so the WebAuthn sign in will work the next time on the current device/browser.

Also notice discoverable credentials are used, i.e. "Sign in with passkey" does not involve the input of an email address. By clicking the button, the browser displays a UI where a credential, stored on the authenticator, can be selected. So no identifier first approach regarding the "Sign in with passkey" button.

Since the WebAuthn Conditional UI feature is announced, please also take into account that the email input will have the ability of the "Sign in with passkey" button. It will be possible to trigger WebAuthn via the autofill menu of the email input, where you can select WebAuthn credentials besides the common email/password logins. This will hopefully improve the UX a lot.

Anyway, it's also true that there have already been discussions at Hanko about splitting the combined login/registration page into separate pages or web components for login and registration, which would be close to your suggestion.

This is all I can tell you about it at the moment. Let me know if I got you right at all and please share your thoughts.

Kind regards

**Comment by SimoMay** [comment]
Great to see! I believe you guys already thought about all this and have solutions to make it better.

**Comment by bjoern-m** [comment]
Alright, I'll merge the PR and close the ticket for now. I assume that we can benefit from the conditional UI feature end of September. Stay tuned!
