### ISSUE TITLE
caddy example

### ISSUE THREAD

**Issue by gedw99** [teamhanko/hanko#868]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

a caddy example 

### Describe your ideal solution

A simple caddy example

Caddy natively support go template now. See: https://caddyserver.com/docs/caddyfile/directives/templates

An Example usage of go templates: https://github.com/caddyserver/website/blob/master/Caddyfile

### Hanko Version

xx

### Additional Context

raised on caddy forum: https://github.com/caddyserver/caddy/tree/master/modules/caddyhttp/caddyauth

**Comment by gedw99** [comment]
Anyone know if https://github.com/teamhanko/hanko-go is still supported ?

**Comment by like-a-bause** [comment]
> Anyone know if https://github.com/teamhanko/hanko-go is still supported ?

No. That client is written for hanko-authentication which is deprecated. Maybe we should archive that one. 

> A simple caddy example

I don't see how this should work. Caddy is a static webserver and does not support JWT Authentication. To protect an API it could merely act as a reverse proxy to another backend service. This is somehow out of scope for hanko examples. Could you elaborate on your request? Otherwise I would mark this as won't do.

**Comment by like-a-bause** [comment]
Will close this now. Feel free to reopen if you have any more insights.

**Comment by gedw99** [comment]
caddy is a proxy, like nginx..

So hanko can be setup behind it as a reverse proxy. 
https://caddyserver.com/docs/quick-starts/reverse-proxy

Also with overmind caddy, hanko and the DB can be run easily from one terminal command.
https://github.com/DarthSim/overmind.
go install github.com/DarthSim/overmind/v2
